In [3]:
#creating a list
my_list=[1,2,3]

In [4]:
#casting a normal list into a array.
import numpy as np
arr=np.array(my_list)
arr

array([1, 2, 3])

In [3]:
#for 2-D array we have to cast a list of list
lst2=[[1,2,3],[4,5,6],[7,8,9]]

In [4]:
lst2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
arr2=np.array(lst2)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
type(arr)

numpy.ndarray

In [7]:
type(arr2)

numpy.ndarray

In [8]:
arr2[0]

array([1, 2, 3])

In [9]:
arr2[0][0]

1

In [10]:
arr2[2][2]

9

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
#zeroes and ones
np.zeros(3)# create only one dimensional array...

array([0., 0., 0.])

In [20]:
#2-d array.
np.zeros((5,5))[2,2] #after creating a 2-D array passing a list of index.

0.0

In [21]:
np.ones(4)

array([1., 1., 1., 1.])

In [23]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
#using linespace...
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [28]:
#to create identity matrices.
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
#using a random methods
np.random.rand(3,3)

array([[0.76742095, 0.89832391, 0.49597548],
       [0.53386964, 0.35863786, 0.32138494],
       [0.7844125 , 0.39669894, 0.7635823 ]])

In [5]:
np.random.randn(5,5)

array([[ 1.45301358,  2.99032061, -0.13819088, -0.5533447 , -1.55799088],
       [-0.89884967,  0.14449515, -0.84552259,  2.65701257,  0.10245952],
       [-0.26297251,  0.21703651, -0.29320595,  0.45569128, -1.31577552],
       [ 0.49612327,  1.74997446,  0.11743219,  1.34212598,  0.77082333],
       [-0.55849374,  0.73789258,  0.90066986,  2.16566009, -1.62976044]])

In [6]:
np.random.randn(2)

array([-3.17439846, -0.13120775])

In [9]:
#using randint -- returns random integers from a low to high
np.random.randint(1,100)

44

In [10]:
np.random.randint(1,100,15)#it is iterating for each value...

array([99, 30, 28, 92, 48, 20, 28,  3, 90, 65, 66, 75, 32,  7, 87])

### Array attributes and methods

In [19]:
arr=np.arange(0,30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [13]:
ranarr=np.random.randint(0,50,10)
ranarr

array([18,  8,  5, 11, 29, 12,  2, 41, 29, 15])

In [23]:
#using reshape keyword..
#no of rows must be equal to number of columns ie must be square
arr.reshape(5,6) # you can check it by multiplying rows and columns which is equal to the no. of elements ina rows.

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

### Max, Min, Argmax,Argmin

In [24]:
ranarr

array([18,  8,  5, 11, 29, 12,  2, 41, 29, 15])

In [30]:
ranarr.argmax()

7

In [31]:
#max
ranarr.max()

41

In [32]:
ranarr.min()

2

In [33]:
ranarr.argmin()

6

In [35]:
arr.dtype#datatype of array.

dtype('int32')

In [34]:
arr.shape #it is an arguement used to create the array of

(30L,)

### numpy Array indexing

In [36]:
arr[4]

4

In [37]:
ranarr[4]

29

In [38]:
ranarr[2:5]

array([ 5, 11, 29])

In [39]:
ranarr[:5]

array([18,  8,  5, 11, 29])

In [40]:
ranarr[5:]

array([12,  2, 41, 29, 15])

### applying broadcast operations on the numpy arrays

In [42]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [43]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [46]:
#assigning a slice of arr array into a new variable.
slcarr=ranarr[2:7]

In [47]:
slcarr

array([ 5, 11, 29, 12,  2])

In [48]:
slcarr[:]=100

In [49]:
slcarr

array([100, 100, 100, 100, 100])

In [50]:
#now checking our origional array. is there is any change or not...
ranarr#change in our origional array.

array([ 18,   8, 100, 100, 100, 100, 100,  41,  29,  15])

In [70]:
#to prevent yourself from above problem we can make a copy of a our origional array.
arr=np.arange(0,25)
arr_copy=arr.copy()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [71]:
arr_copy#both are same

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [72]:
arr_copy[:]=100

In [73]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [74]:
arr#our origional array remains same.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [75]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [76]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [77]:
#grabbing indexes from the 2-d array.
arr_2d[0][0]

5

In [78]:
#method 2 to grab
arr_2d[1,2]

30

In [82]:
arr_2d[:2,1:]#note inclusive and exclusive index notation here 2 is exclusive and 1 is inclusive

array([[10, 15],
       [25, 30]])

In [84]:
new_arr=np.arange(0,11)
new_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
#we will check with conditional operator to get the boolean array.
bool_arr= new_arr>5
bool_arr
#type(bool_arr)

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [90]:
new_arr[bool_arr]

array([ 6,  7,  8,  9, 10])

# NUMPY OPERATIONS

In [91]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [92]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [94]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576])

In [95]:
arr/arr

C:\Users\user\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in divide
  """Entry point for launching an IPython kernel.


array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1])

In [96]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124])

In [97]:
arr-100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90,
        -89,  -88,  -87,  -86,  -85,  -84,  -83,  -82,  -81,  -80,  -79,
        -78,  -77,  -76])

In [98]:
1/arr

C:\Users\user\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in divide
  """Entry point for launching an IPython kernel.


array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0])

In [99]:
arr/arr

C:\Users\user\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in divide
  """Entry point for launching an IPython kernel.


array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1])

In [100]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576])

### universal array functions

In [102]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949])

In [103]:
np.info(arr)

class:  ndarray
shape:  (25L,)
strides:  (4L,)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x478f180L
byteorder:  little
byteswap:  False
type: int32


In [104]:
np.max(arr)

24

In [105]:
np.min(arr)

0

In [106]:
np.argmax(arr)

24

In [107]:
np.argmin(arr)

0

In [109]:
np.sum(arr)

300

In [112]:
np.multiply(arr,arr)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576])

In [113]:
np.log(arr)

C:\Users\user\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383])

In [114]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721,
        0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836])